[package]
name = "semverguard-engine"
version = "0.1.0"
description = "Semver engine adapter that runs cargo semver-checks check-release."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/semverguard-engine"
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
semverguard-domain = { version = "0.1.0", path = "../semverguard-domain" }
semverguard-types = { version = "0.1.0", path = "../semverguard-types" }

[dev-dependencies]
tempfile = "3.24.0"

[lints]
workspace = true
